// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	requests "hopSpotAPI/internal/dto/requests"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

type AdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminService) EXPECT() *AdminService_Expecter {
	return &AdminService_Expecter{mock: &_m.Mock}
}

// CreateInvitationCode provides a mock function with given fields: ctx, req, adminID
func (_m *AdminService) CreateInvitationCode(ctx context.Context, req *requests.CreateInvitationCodeRequest, adminID uint) (*responses.InvitationCodeResponse, error) {
	ret := _m.Called(ctx, req, adminID)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitationCode")
	}

	var r0 *responses.InvitationCodeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateInvitationCodeRequest, uint) (*responses.InvitationCodeResponse, error)); ok {
		return rf(ctx, req, adminID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateInvitationCodeRequest, uint) *responses.InvitationCodeResponse); ok {
		r0 = rf(ctx, req, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.InvitationCodeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.CreateInvitationCodeRequest, uint) error); ok {
		r1 = rf(ctx, req, adminID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_CreateInvitationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitationCode'
type AdminService_CreateInvitationCode_Call struct {
	*mock.Call
}

// CreateInvitationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.CreateInvitationCodeRequest
//   - adminID uint
func (_e *AdminService_Expecter) CreateInvitationCode(ctx interface{}, req interface{}, adminID interface{}) *AdminService_CreateInvitationCode_Call {
	return &AdminService_CreateInvitationCode_Call{Call: _e.mock.On("CreateInvitationCode", ctx, req, adminID)}
}

func (_c *AdminService_CreateInvitationCode_Call) Run(run func(ctx context.Context, req *requests.CreateInvitationCodeRequest, adminID uint)) *AdminService_CreateInvitationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.CreateInvitationCodeRequest), args[2].(uint))
	})
	return _c
}

func (_c *AdminService_CreateInvitationCode_Call) Return(_a0 *responses.InvitationCodeResponse, _a1 error) *AdminService_CreateInvitationCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_CreateInvitationCode_Call) RunAndReturn(run func(context.Context, *requests.CreateInvitationCodeRequest, uint) (*responses.InvitationCodeResponse, error)) *AdminService_CreateInvitationCode_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id, adminID
func (_m *AdminService) DeleteUser(ctx context.Context, id uint, adminID uint) error {
	ret := _m.Called(ctx, id, adminID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, id, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type AdminService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - adminID uint
func (_e *AdminService_Expecter) DeleteUser(ctx interface{}, id interface{}, adminID interface{}) *AdminService_DeleteUser_Call {
	return &AdminService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id, adminID)}
}

func (_c *AdminService_DeleteUser_Call) Run(run func(ctx context.Context, id uint, adminID uint)) *AdminService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *AdminService_DeleteUser_Call) Return(_a0 error) *AdminService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminService_DeleteUser_Call) RunAndReturn(run func(context.Context, uint, uint) error) *AdminService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvitationCodes provides a mock function with given fields: ctx, req
func (_m *AdminService) ListInvitationCodes(ctx context.Context, req *requests.ListInvitationCodesRequest) (*responses.PaginatedInvitationCodesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInvitationCodes")
	}

	var r0 *responses.PaginatedInvitationCodesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListInvitationCodesRequest) (*responses.PaginatedInvitationCodesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListInvitationCodesRequest) *responses.PaginatedInvitationCodesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PaginatedInvitationCodesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.ListInvitationCodesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_ListInvitationCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvitationCodes'
type AdminService_ListInvitationCodes_Call struct {
	*mock.Call
}

// ListInvitationCodes is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.ListInvitationCodesRequest
func (_e *AdminService_Expecter) ListInvitationCodes(ctx interface{}, req interface{}) *AdminService_ListInvitationCodes_Call {
	return &AdminService_ListInvitationCodes_Call{Call: _e.mock.On("ListInvitationCodes", ctx, req)}
}

func (_c *AdminService_ListInvitationCodes_Call) Run(run func(ctx context.Context, req *requests.ListInvitationCodesRequest)) *AdminService_ListInvitationCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.ListInvitationCodesRequest))
	})
	return _c
}

func (_c *AdminService_ListInvitationCodes_Call) Return(_a0 *responses.PaginatedInvitationCodesResponse, _a1 error) *AdminService_ListInvitationCodes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_ListInvitationCodes_Call) RunAndReturn(run func(context.Context, *requests.ListInvitationCodesRequest) (*responses.PaginatedInvitationCodesResponse, error)) *AdminService_ListInvitationCodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, req
func (_m *AdminService) ListUsers(ctx context.Context, req *requests.ListUsersRequest) (*responses.PaginatedUsersResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *responses.PaginatedUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListUsersRequest) (*responses.PaginatedUsersResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListUsersRequest) *responses.PaginatedUsersResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PaginatedUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.ListUsersRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type AdminService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.ListUsersRequest
func (_e *AdminService_Expecter) ListUsers(ctx interface{}, req interface{}) *AdminService_ListUsers_Call {
	return &AdminService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, req)}
}

func (_c *AdminService_ListUsers_Call) Run(run func(ctx context.Context, req *requests.ListUsersRequest)) *AdminService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.ListUsersRequest))
	})
	return _c
}

func (_c *AdminService_ListUsers_Call) Return(_a0 *responses.PaginatedUsersResponse, _a1 error) *AdminService_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_ListUsers_Call) RunAndReturn(run func(context.Context, *requests.ListUsersRequest) (*responses.PaginatedUsersResponse, error)) *AdminService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, id, req
func (_m *AdminService) UpdateUser(ctx context.Context, id uint, req *requests.AdminUpdateUserRequest) (*responses.UserResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *responses.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.AdminUpdateUserRequest) (*responses.UserResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.AdminUpdateUserRequest) *responses.UserResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *requests.AdminUpdateUserRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type AdminService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req *requests.AdminUpdateUserRequest
func (_e *AdminService_Expecter) UpdateUser(ctx interface{}, id interface{}, req interface{}) *AdminService_UpdateUser_Call {
	return &AdminService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, req)}
}

func (_c *AdminService_UpdateUser_Call) Run(run func(ctx context.Context, id uint, req *requests.AdminUpdateUserRequest)) *AdminService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*requests.AdminUpdateUserRequest))
	})
	return _c
}

func (_c *AdminService_UpdateUser_Call) Return(_a0 *responses.UserResponse, _a1 error) *AdminService_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_UpdateUser_Call) RunAndReturn(run func(context.Context, uint, *requests.AdminUpdateUserRequest) (*responses.UserResponse, error)) *AdminService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
