// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	requests "hopSpotAPI/internal/dto/requests"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req
func (_m *AuthService) Login(ctx context.Context, req *requests.LoginRequest) (*responses.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *responses.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.LoginRequest) (*responses.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.LoginRequest) *responses.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.LoginRequest
func (_e *AuthService_Expecter) Login(ctx interface{}, req interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *AuthService_Login_Call) Run(run func(ctx context.Context, req *requests.LoginRequest)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.LoginRequest))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 *responses.LoginResponse, _a1 error) *AuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(context.Context, *requests.LoginRequest) (*responses.LoginResponse, error)) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, req
func (_m *AuthService) Logout(ctx context.Context, req *requests.LogoutRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.LogoutRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.LogoutRequest
func (_e *AuthService_Expecter) Logout(ctx interface{}, req interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, req)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, req *requests.LogoutRequest)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.LogoutRequest))
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(_a0 error) *AuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(context.Context, *requests.LogoutRequest) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, req
func (_m *AuthService) Refresh(ctx context.Context, req *requests.RefreshTokenRequest) (*responses.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *responses.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.RefreshTokenRequest) (*responses.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.RefreshTokenRequest) *responses.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.RefreshTokenRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.RefreshTokenRequest
func (_e *AuthService_Expecter) Refresh(ctx interface{}, req interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, req)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, req *requests.RefreshTokenRequest)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.RefreshTokenRequest))
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(_a0 *responses.LoginResponse, _a1 error) *AuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(context.Context, *requests.RefreshTokenRequest) (*responses.LoginResponse, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshFCMToken provides a mock function with given fields: ctx, userId, fcmToken
func (_m *AuthService) RefreshFCMToken(ctx context.Context, userId uint, fcmToken string) error {
	ret := _m.Called(ctx, userId, fcmToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshFCMToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) error); ok {
		r0 = rf(ctx, userId, fcmToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_RefreshFCMToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshFCMToken'
type AuthService_RefreshFCMToken_Call struct {
	*mock.Call
}

// RefreshFCMToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - fcmToken string
func (_e *AuthService_Expecter) RefreshFCMToken(ctx interface{}, userId interface{}, fcmToken interface{}) *AuthService_RefreshFCMToken_Call {
	return &AuthService_RefreshFCMToken_Call{Call: _e.mock.On("RefreshFCMToken", ctx, userId, fcmToken)}
}

func (_c *AuthService_RefreshFCMToken_Call) Run(run func(ctx context.Context, userId uint, fcmToken string)) *AuthService_RefreshFCMToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *AuthService_RefreshFCMToken_Call) Return(_a0 error) *AuthService_RefreshFCMToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_RefreshFCMToken_Call) RunAndReturn(run func(context.Context, uint, string) error) *AuthService_RefreshFCMToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req *requests.RegisterRequest) (*responses.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *responses.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.RegisterRequest) (*responses.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.RegisterRequest) *responses.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.RegisterRequest
func (_e *AuthService_Expecter) Register(ctx interface{}, req interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, req *requests.RegisterRequest)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.RegisterRequest))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *responses.LoginResponse, _a1 error) *AuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(context.Context, *requests.RegisterRequest) (*responses.LoginResponse, error)) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
