// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "hopSpotAPI/internal/repository"
)

// InvitationRepository is an autogenerated mock type for the InvitationRepository type
type InvitationRepository struct {
	mock.Mock
}

type InvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InvitationRepository) EXPECT() *InvitationRepository_Expecter {
	return &InvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, code
func (_m *InvitationRepository) Create(ctx context.Context, code *domain.InvitationCode) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.InvitationCode) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type InvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - code *domain.InvitationCode
func (_e *InvitationRepository_Expecter) Create(ctx interface{}, code interface{}) *InvitationRepository_Create_Call {
	return &InvitationRepository_Create_Call{Call: _e.mock.On("Create", ctx, code)}
}

func (_c *InvitationRepository_Create_Call) Run(run func(ctx context.Context, code *domain.InvitationCode)) *InvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.InvitationCode))
	})
	return _c
}

func (_c *InvitationRepository_Create_Call) Return(_a0 error) *InvitationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.InvitationCode) error) *InvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *InvitationRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type InvitationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *InvitationRepository_Expecter) Delete(ctx interface{}, id interface{}) *InvitationRepository_Delete_Call {
	return &InvitationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *InvitationRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *InvitationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *InvitationRepository_Delete_Call) Return(_a0 error) *InvitationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *InvitationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *InvitationRepository) FindAll(ctx context.Context, filter repository.InvitationFilter) ([]domain.InvitationCode, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.InvitationCode
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.InvitationFilter) ([]domain.InvitationCode, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.InvitationFilter) []domain.InvitationCode); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InvitationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.InvitationFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.InvitationFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InvitationRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type InvitationRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.InvitationFilter
func (_e *InvitationRepository_Expecter) FindAll(ctx interface{}, filter interface{}) *InvitationRepository_FindAll_Call {
	return &InvitationRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *InvitationRepository_FindAll_Call) Run(run func(ctx context.Context, filter repository.InvitationFilter)) *InvitationRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.InvitationFilter))
	})
	return _c
}

func (_c *InvitationRepository_FindAll_Call) Return(_a0 []domain.InvitationCode, _a1 int64, _a2 error) *InvitationRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *InvitationRepository_FindAll_Call) RunAndReturn(run func(context.Context, repository.InvitationFilter) ([]domain.InvitationCode, int64, error)) *InvitationRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *InvitationRepository) FindByCode(ctx context.Context, code string) (*domain.InvitationCode, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *domain.InvitationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.InvitationCode, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.InvitationCode); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InvitationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type InvitationRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *InvitationRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *InvitationRepository_FindByCode_Call {
	return &InvitationRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *InvitationRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *InvitationRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InvitationRepository_FindByCode_Call) Return(_a0 *domain.InvitationCode, _a1 error) *InvitationRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (*domain.InvitationCode, error)) *InvitationRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *InvitationRepository) FindByID(ctx context.Context, id uint) (*domain.InvitationCode, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.InvitationCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.InvitationCode, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.InvitationCode); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InvitationCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvitationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type InvitationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *InvitationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *InvitationRepository_FindByID_Call {
	return &InvitationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *InvitationRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *InvitationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *InvitationRepository_FindByID_Call) Return(_a0 *domain.InvitationCode, _a1 error) *InvitationRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InvitationRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.InvitationCode, error)) *InvitationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRedeemed provides a mock function with given fields: ctx, codeID, userID
func (_m *InvitationRepository) MarkAsRedeemed(ctx context.Context, codeID uint, userID uint) error {
	ret := _m.Called(ctx, codeID, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRedeemed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, codeID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_MarkAsRedeemed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRedeemed'
type InvitationRepository_MarkAsRedeemed_Call struct {
	*mock.Call
}

// MarkAsRedeemed is a helper method to define mock.On call
//   - ctx context.Context
//   - codeID uint
//   - userID uint
func (_e *InvitationRepository_Expecter) MarkAsRedeemed(ctx interface{}, codeID interface{}, userID interface{}) *InvitationRepository_MarkAsRedeemed_Call {
	return &InvitationRepository_MarkAsRedeemed_Call{Call: _e.mock.On("MarkAsRedeemed", ctx, codeID, userID)}
}

func (_c *InvitationRepository_MarkAsRedeemed_Call) Run(run func(ctx context.Context, codeID uint, userID uint)) *InvitationRepository_MarkAsRedeemed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *InvitationRepository_MarkAsRedeemed_Call) Return(_a0 error) *InvitationRepository_MarkAsRedeemed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_MarkAsRedeemed_Call) RunAndReturn(run func(context.Context, uint, uint) error) *InvitationRepository_MarkAsRedeemed_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, code
func (_m *InvitationRepository) Update(ctx context.Context, code *domain.InvitationCode) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.InvitationCode) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvitationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type InvitationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - code *domain.InvitationCode
func (_e *InvitationRepository_Expecter) Update(ctx interface{}, code interface{}) *InvitationRepository_Update_Call {
	return &InvitationRepository_Update_Call{Call: _e.mock.On("Update", ctx, code)}
}

func (_c *InvitationRepository_Update_Call) Run(run func(ctx context.Context, code *domain.InvitationCode)) *InvitationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.InvitationCode))
	})
	return _c
}

func (_c *InvitationRepository_Update_Call) Return(_a0 error) *InvitationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InvitationRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.InvitationCode) error) *InvitationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewInvitationRepository creates a new instance of InvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InvitationRepository {
	mock := &InvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
