// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// NotifyNewSpot provides a mock function with given fields: ctx, spot, creatorID
func (_m *NotificationService) NotifyNewSpot(ctx context.Context, spot *domain.Spot, creatorID uint) error {
	ret := _m.Called(ctx, spot, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyNewSpot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spot, uint) error); ok {
		r0 = rf(ctx, spot, creatorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_NotifyNewSpot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyNewSpot'
type NotificationService_NotifyNewSpot_Call struct {
	*mock.Call
}

// NotifyNewSpot is a helper method to define mock.On call
//   - ctx context.Context
//   - spot *domain.Spot
//   - creatorID uint
func (_e *NotificationService_Expecter) NotifyNewSpot(ctx interface{}, spot interface{}, creatorID interface{}) *NotificationService_NotifyNewSpot_Call {
	return &NotificationService_NotifyNewSpot_Call{Call: _e.mock.On("NotifyNewSpot", ctx, spot, creatorID)}
}

func (_c *NotificationService_NotifyNewSpot_Call) Run(run func(ctx context.Context, spot *domain.Spot, creatorID uint)) *NotificationService_NotifyNewSpot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Spot), args[2].(uint))
	})
	return _c
}

func (_c *NotificationService_NotifyNewSpot_Call) Return(_a0 error) *NotificationService_NotifyNewSpot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotificationService_NotifyNewSpot_Call) RunAndReturn(run func(context.Context, *domain.Spot, uint) error) *NotificationService_NotifyNewSpot_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
