// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// PhotoRepository is an autogenerated mock type for the PhotoRepository type
type PhotoRepository struct {
	mock.Mock
}

type PhotoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PhotoRepository) EXPECT() *PhotoRepository_Expecter {
	return &PhotoRepository_Expecter{mock: &_m.Mock}
}

// CountByBenchID provides a mock function with given fields: ctx, benchID
func (_m *PhotoRepository) CountByBenchID(ctx context.Context, benchID uint) (int64, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBenchID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, benchID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoRepository_CountByBenchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBenchID'
type PhotoRepository_CountByBenchID_Call struct {
	*mock.Call
}

// CountByBenchID is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *PhotoRepository_Expecter) CountByBenchID(ctx interface{}, benchID interface{}) *PhotoRepository_CountByBenchID_Call {
	return &PhotoRepository_CountByBenchID_Call{Call: _e.mock.On("CountByBenchID", ctx, benchID)}
}

func (_c *PhotoRepository_CountByBenchID_Call) Run(run func(ctx context.Context, benchID uint)) *PhotoRepository_CountByBenchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoRepository_CountByBenchID_Call) Return(_a0 int64, _a1 error) *PhotoRepository_CountByBenchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoRepository_CountByBenchID_Call) RunAndReturn(run func(context.Context, uint) (int64, error)) *PhotoRepository_CountByBenchID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, photo
func (_m *PhotoRepository) Create(ctx context.Context, photo *domain.Photo) error {
	ret := _m.Called(ctx, photo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Photo) error); ok {
		r0 = rf(ctx, photo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PhotoRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - photo *domain.Photo
func (_e *PhotoRepository_Expecter) Create(ctx interface{}, photo interface{}) *PhotoRepository_Create_Call {
	return &PhotoRepository_Create_Call{Call: _e.mock.On("Create", ctx, photo)}
}

func (_c *PhotoRepository_Create_Call) Run(run func(ctx context.Context, photo *domain.Photo)) *PhotoRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Photo))
	})
	return _c
}

func (_c *PhotoRepository_Create_Call) Return(_a0 error) *PhotoRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Photo) error) *PhotoRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PhotoRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PhotoRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *PhotoRepository_Expecter) Delete(ctx interface{}, id interface{}) *PhotoRepository_Delete_Call {
	return &PhotoRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PhotoRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *PhotoRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoRepository_Delete_Call) Return(_a0 error) *PhotoRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *PhotoRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBenchID provides a mock function with given fields: ctx, benchID
func (_m *PhotoRepository) FindByBenchID(ctx context.Context, benchID uint) ([]domain.Photo, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBenchID")
	}

	var r0 []domain.Photo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Photo, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Photo); ok {
		r0 = rf(ctx, benchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Photo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoRepository_FindByBenchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBenchID'
type PhotoRepository_FindByBenchID_Call struct {
	*mock.Call
}

// FindByBenchID is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *PhotoRepository_Expecter) FindByBenchID(ctx interface{}, benchID interface{}) *PhotoRepository_FindByBenchID_Call {
	return &PhotoRepository_FindByBenchID_Call{Call: _e.mock.On("FindByBenchID", ctx, benchID)}
}

func (_c *PhotoRepository_FindByBenchID_Call) Run(run func(ctx context.Context, benchID uint)) *PhotoRepository_FindByBenchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoRepository_FindByBenchID_Call) Return(_a0 []domain.Photo, _a1 error) *PhotoRepository_FindByBenchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoRepository_FindByBenchID_Call) RunAndReturn(run func(context.Context, uint) ([]domain.Photo, error)) *PhotoRepository_FindByBenchID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PhotoRepository) FindByID(ctx context.Context, id uint) (*domain.Photo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Photo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Photo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Photo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Photo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PhotoRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *PhotoRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PhotoRepository_FindByID_Call {
	return &PhotoRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PhotoRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *PhotoRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoRepository_FindByID_Call) Return(_a0 *domain.Photo, _a1 error) *PhotoRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Photo, error)) *PhotoRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMainPhoto provides a mock function with given fields: ctx, benchID
func (_m *PhotoRepository) GetMainPhoto(ctx context.Context, benchID uint) (*domain.Photo, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for GetMainPhoto")
	}

	var r0 *domain.Photo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Photo, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Photo); ok {
		r0 = rf(ctx, benchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Photo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoRepository_GetMainPhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainPhoto'
type PhotoRepository_GetMainPhoto_Call struct {
	*mock.Call
}

// GetMainPhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *PhotoRepository_Expecter) GetMainPhoto(ctx interface{}, benchID interface{}) *PhotoRepository_GetMainPhoto_Call {
	return &PhotoRepository_GetMainPhoto_Call{Call: _e.mock.On("GetMainPhoto", ctx, benchID)}
}

func (_c *PhotoRepository_GetMainPhoto_Call) Run(run func(ctx context.Context, benchID uint)) *PhotoRepository_GetMainPhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoRepository_GetMainPhoto_Call) Return(_a0 *domain.Photo, _a1 error) *PhotoRepository_GetMainPhoto_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoRepository_GetMainPhoto_Call) RunAndReturn(run func(context.Context, uint) (*domain.Photo, error)) *PhotoRepository_GetMainPhoto_Call {
	_c.Call.Return(run)
	return _c
}

// SetMainPhoto provides a mock function with given fields: ctx, photoID, benchID
func (_m *PhotoRepository) SetMainPhoto(ctx context.Context, photoID uint, benchID uint) error {
	ret := _m.Called(ctx, photoID, benchID)

	if len(ret) == 0 {
		panic("no return value specified for SetMainPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, photoID, benchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoRepository_SetMainPhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMainPhoto'
type PhotoRepository_SetMainPhoto_Call struct {
	*mock.Call
}

// SetMainPhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - photoID uint
//   - benchID uint
func (_e *PhotoRepository_Expecter) SetMainPhoto(ctx interface{}, photoID interface{}, benchID interface{}) *PhotoRepository_SetMainPhoto_Call {
	return &PhotoRepository_SetMainPhoto_Call{Call: _e.mock.On("SetMainPhoto", ctx, photoID, benchID)}
}

func (_c *PhotoRepository_SetMainPhoto_Call) Run(run func(ctx context.Context, photoID uint, benchID uint)) *PhotoRepository_SetMainPhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint))
	})
	return _c
}

func (_c *PhotoRepository_SetMainPhoto_Call) Return(_a0 error) *PhotoRepository_SetMainPhoto_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoRepository_SetMainPhoto_Call) RunAndReturn(run func(context.Context, uint, uint) error) *PhotoRepository_SetMainPhoto_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, photo
func (_m *PhotoRepository) Update(ctx context.Context, photo *domain.Photo) error {
	ret := _m.Called(ctx, photo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Photo) error); ok {
		r0 = rf(ctx, photo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PhotoRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - photo *domain.Photo
func (_e *PhotoRepository_Expecter) Update(ctx interface{}, photo interface{}) *PhotoRepository_Update_Call {
	return &PhotoRepository_Update_Call{Call: _e.mock.On("Update", ctx, photo)}
}

func (_c *PhotoRepository_Update_Call) Run(run func(ctx context.Context, photo *domain.Photo)) *PhotoRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Photo))
	})
	return _c
}

func (_c *PhotoRepository_Update_Call) Return(_a0 error) *PhotoRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Photo) error) *PhotoRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPhotoRepository creates a new instance of PhotoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPhotoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PhotoRepository {
	mock := &PhotoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
