// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// PhotoService is an autogenerated mock type for the PhotoService type
type PhotoService struct {
	mock.Mock
}

type PhotoService_Expecter struct {
	mock *mock.Mock
}

func (_m *PhotoService) EXPECT() *PhotoService_Expecter {
	return &PhotoService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, photoID, userID, isAdmin
func (_m *PhotoService) Delete(ctx context.Context, photoID uint, userID uint, isAdmin bool) error {
	ret := _m.Called(ctx, photoID, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, bool) error); ok {
		r0 = rf(ctx, photoID, userID, isAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PhotoService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - photoID uint
//   - userID uint
//   - isAdmin bool
func (_e *PhotoService_Expecter) Delete(ctx interface{}, photoID interface{}, userID interface{}, isAdmin interface{}) *PhotoService_Delete_Call {
	return &PhotoService_Delete_Call{Call: _e.mock.On("Delete", ctx, photoID, userID, isAdmin)}
}

func (_c *PhotoService_Delete_Call) Run(run func(ctx context.Context, photoID uint, userID uint, isAdmin bool)) *PhotoService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(bool))
	})
	return _c
}

func (_c *PhotoService_Delete_Call) Return(_a0 error) *PhotoService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoService_Delete_Call) RunAndReturn(run func(context.Context, uint, uint, bool) error) *PhotoService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBenchID provides a mock function with given fields: ctx, benchID
func (_m *PhotoService) GetByBenchID(ctx context.Context, benchID uint) ([]responses.PhotoResponse, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBenchID")
	}

	var r0 []responses.PhotoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]responses.PhotoResponse, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []responses.PhotoResponse); ok {
		r0 = rf(ctx, benchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.PhotoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoService_GetByBenchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBenchID'
type PhotoService_GetByBenchID_Call struct {
	*mock.Call
}

// GetByBenchID is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *PhotoService_Expecter) GetByBenchID(ctx interface{}, benchID interface{}) *PhotoService_GetByBenchID_Call {
	return &PhotoService_GetByBenchID_Call{Call: _e.mock.On("GetByBenchID", ctx, benchID)}
}

func (_c *PhotoService_GetByBenchID_Call) Run(run func(ctx context.Context, benchID uint)) *PhotoService_GetByBenchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PhotoService_GetByBenchID_Call) Return(_a0 []responses.PhotoResponse, _a1 error) *PhotoService_GetByBenchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoService_GetByBenchID_Call) RunAndReturn(run func(context.Context, uint) ([]responses.PhotoResponse, error)) *PhotoService_GetByBenchID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function with given fields: ctx, photoID, size
func (_m *PhotoService) GetPresignedURL(ctx context.Context, photoID uint, size string) (string, error) {
	ret := _m.Called(ctx, photoID, size)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) (string, error)); ok {
		return rf(ctx, photoID, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) string); ok {
		r0 = rf(ctx, photoID, size)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, photoID, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoService_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type PhotoService_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - photoID uint
//   - size string
func (_e *PhotoService_Expecter) GetPresignedURL(ctx interface{}, photoID interface{}, size interface{}) *PhotoService_GetPresignedURL_Call {
	return &PhotoService_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, photoID, size)}
}

func (_c *PhotoService_GetPresignedURL_Call) Run(run func(ctx context.Context, photoID uint, size string)) *PhotoService_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string))
	})
	return _c
}

func (_c *PhotoService_GetPresignedURL_Call) Return(_a0 string, _a1 error) *PhotoService_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoService_GetPresignedURL_Call) RunAndReturn(run func(context.Context, uint, string) (string, error)) *PhotoService_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// SetMainPhoto provides a mock function with given fields: ctx, photoID, userID, isAdmin
func (_m *PhotoService) SetMainPhoto(ctx context.Context, photoID uint, userID uint, isAdmin bool) error {
	ret := _m.Called(ctx, photoID, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for SetMainPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, bool) error); ok {
		r0 = rf(ctx, photoID, userID, isAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PhotoService_SetMainPhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMainPhoto'
type PhotoService_SetMainPhoto_Call struct {
	*mock.Call
}

// SetMainPhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - photoID uint
//   - userID uint
//   - isAdmin bool
func (_e *PhotoService_Expecter) SetMainPhoto(ctx interface{}, photoID interface{}, userID interface{}, isAdmin interface{}) *PhotoService_SetMainPhoto_Call {
	return &PhotoService_SetMainPhoto_Call{Call: _e.mock.On("SetMainPhoto", ctx, photoID, userID, isAdmin)}
}

func (_c *PhotoService_SetMainPhoto_Call) Run(run func(ctx context.Context, photoID uint, userID uint, isAdmin bool)) *PhotoService_SetMainPhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(bool))
	})
	return _c
}

func (_c *PhotoService_SetMainPhoto_Call) Return(_a0 error) *PhotoService_SetMainPhoto_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PhotoService_SetMainPhoto_Call) RunAndReturn(run func(context.Context, uint, uint, bool) error) *PhotoService_SetMainPhoto_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, benchID, userID, file, isMain
func (_m *PhotoService) Upload(ctx context.Context, benchID uint, userID uint, file *multipart.FileHeader, isMain bool) (*responses.PhotoResponse, error) {
	ret := _m.Called(ctx, benchID, userID, file, isMain)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *responses.PhotoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *multipart.FileHeader, bool) (*responses.PhotoResponse, error)); ok {
		return rf(ctx, benchID, userID, file, isMain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, *multipart.FileHeader, bool) *responses.PhotoResponse); ok {
		r0 = rf(ctx, benchID, userID, file, isMain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PhotoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, *multipart.FileHeader, bool) error); ok {
		r1 = rf(ctx, benchID, userID, file, isMain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type PhotoService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
//   - userID uint
//   - file *multipart.FileHeader
//   - isMain bool
func (_e *PhotoService_Expecter) Upload(ctx interface{}, benchID interface{}, userID interface{}, file interface{}, isMain interface{}) *PhotoService_Upload_Call {
	return &PhotoService_Upload_Call{Call: _e.mock.On("Upload", ctx, benchID, userID, file, isMain)}
}

func (_c *PhotoService_Upload_Call) Run(run func(ctx context.Context, benchID uint, userID uint, file *multipart.FileHeader, isMain bool)) *PhotoService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(*multipart.FileHeader), args[4].(bool))
	})
	return _c
}

func (_c *PhotoService_Upload_Call) Return(_a0 *responses.PhotoResponse, _a1 error) *PhotoService_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PhotoService_Upload_Call) RunAndReturn(run func(context.Context, uint, uint, *multipart.FileHeader, bool) (*responses.PhotoResponse, error)) *PhotoService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewPhotoService creates a new instance of PhotoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPhotoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PhotoService {
	mock := &PhotoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
