// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *RefreshTokenRepository) Create(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(_a0 error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *RefreshTokenRepository) DeleteExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type RefreshTokenRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RefreshTokenRepository_Expecter) DeleteExpired(ctx interface{}) *RefreshTokenRepository_DeleteExpired_Call {
	return &RefreshTokenRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *RefreshTokenRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *RefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RefreshTokenRepository_DeleteExpired_Call) Return(_a0 error) *RefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) error) *RefreshTokenRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *RefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type RefreshTokenRepository_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RefreshTokenRepository_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *RefreshTokenRepository_FindByTokenHash_Call {
	return &RefreshTokenRepository_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) Return(_a0 *domain.RefreshToken, _a1 error) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *RefreshTokenRepository) RevokeByID(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type RefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *RefreshTokenRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *RefreshTokenRepository_RevokeByID_Call {
	return &RefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *RefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uint)) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByID_Call) Return(_a0 error) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, uint) error) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByUserID provides a mock function with given fields: ctx, userID
func (_m *RefreshTokenRepository) RevokeByUserID(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_RevokeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByUserID'
type RefreshTokenRepository_RevokeByUserID_Call struct {
	*mock.Call
}

// RevokeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *RefreshTokenRepository_Expecter) RevokeByUserID(ctx interface{}, userID interface{}) *RefreshTokenRepository_RevokeByUserID_Call {
	return &RefreshTokenRepository_RevokeByUserID_Call{Call: _e.mock.On("RevokeByUserID", ctx, userID)}
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) Run(run func(ctx context.Context, userID uint)) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) Return(_a0 error) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) RunAndReturn(run func(context.Context, uint) error) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
