// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	requests "hopSpotAPI/internal/dto/requests"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// SpotService is an autogenerated mock type for the SpotService type
type SpotService struct {
	mock.Mock
}

type SpotService_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotService) EXPECT() *SpotService_Expecter {
	return &SpotService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req, userID
func (_m *SpotService) Create(ctx context.Context, req *requests.CreateSpotRequest, userID uint) (*responses.SpotResponse, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *responses.SpotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateSpotRequest, uint) (*responses.SpotResponse, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateSpotRequest, uint) *responses.SpotResponse); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.SpotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.CreateSpotRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SpotService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.CreateSpotRequest
//   - userID uint
func (_e *SpotService_Expecter) Create(ctx interface{}, req interface{}, userID interface{}) *SpotService_Create_Call {
	return &SpotService_Create_Call{Call: _e.mock.On("Create", ctx, req, userID)}
}

func (_c *SpotService_Create_Call) Run(run func(ctx context.Context, req *requests.CreateSpotRequest, userID uint)) *SpotService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.CreateSpotRequest), args[2].(uint))
	})
	return _c
}

func (_c *SpotService_Create_Call) Return(_a0 *responses.SpotResponse, _a1 error) *SpotService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotService_Create_Call) RunAndReturn(run func(context.Context, *requests.CreateSpotRequest, uint) (*responses.SpotResponse, error)) *SpotService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, userID, isAdmin
func (_m *SpotService) Delete(ctx context.Context, id uint, userID uint, isAdmin bool) error {
	ret := _m.Called(ctx, id, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, bool) error); ok {
		r0 = rf(ctx, id, userID, isAdmin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SpotService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - userID uint
//   - isAdmin bool
func (_e *SpotService_Expecter) Delete(ctx interface{}, id interface{}, userID interface{}, isAdmin interface{}) *SpotService_Delete_Call {
	return &SpotService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, userID, isAdmin)}
}

func (_c *SpotService_Delete_Call) Run(run func(ctx context.Context, id uint, userID uint, isAdmin bool)) *SpotService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(bool))
	})
	return _c
}

func (_c *SpotService_Delete_Call) Return(_a0 error) *SpotService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotService_Delete_Call) RunAndReturn(run func(context.Context, uint, uint, bool) error) *SpotService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *SpotService) GetByID(ctx context.Context, id uint) (*responses.SpotResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *responses.SpotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*responses.SpotResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *responses.SpotResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.SpotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SpotService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *SpotService_Expecter) GetByID(ctx interface{}, id interface{}) *SpotService_GetByID_Call {
	return &SpotService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *SpotService_GetByID_Call) Run(run func(ctx context.Context, id uint)) *SpotService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *SpotService_GetByID_Call) Return(_a0 *responses.SpotResponse, _a1 error) *SpotService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotService_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*responses.SpotResponse, error)) *SpotService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandom provides a mock function with given fields: ctx
func (_m *SpotService) GetRandom(ctx context.Context) (*responses.SpotResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandom")
	}

	var r0 *responses.SpotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*responses.SpotResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *responses.SpotResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.SpotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotService_GetRandom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandom'
type SpotService_GetRandom_Call struct {
	*mock.Call
}

// GetRandom is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotService_Expecter) GetRandom(ctx interface{}) *SpotService_GetRandom_Call {
	return &SpotService_GetRandom_Call{Call: _e.mock.On("GetRandom", ctx)}
}

func (_c *SpotService_GetRandom_Call) Run(run func(ctx context.Context)) *SpotService_GetRandom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotService_GetRandom_Call) Return(_a0 *responses.SpotResponse, _a1 error) *SpotService_GetRandom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotService_GetRandom_Call) RunAndReturn(run func(context.Context) (*responses.SpotResponse, error)) *SpotService_GetRandom_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req
func (_m *SpotService) List(ctx context.Context, req *requests.ListSpotsRequest) (*responses.PaginatedSpotsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *responses.PaginatedSpotsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListSpotsRequest) (*responses.PaginatedSpotsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListSpotsRequest) *responses.PaginatedSpotsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PaginatedSpotsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.ListSpotsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SpotService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.ListSpotsRequest
func (_e *SpotService_Expecter) List(ctx interface{}, req interface{}) *SpotService_List_Call {
	return &SpotService_List_Call{Call: _e.mock.On("List", ctx, req)}
}

func (_c *SpotService_List_Call) Run(run func(ctx context.Context, req *requests.ListSpotsRequest)) *SpotService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.ListSpotsRequest))
	})
	return _c
}

func (_c *SpotService_List_Call) Return(_a0 *responses.PaginatedSpotsResponse, _a1 error) *SpotService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotService_List_Call) RunAndReturn(run func(context.Context, *requests.ListSpotsRequest) (*responses.PaginatedSpotsResponse, error)) *SpotService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req, userID, isAdmin
func (_m *SpotService) Update(ctx context.Context, id uint, req *requests.UpdateSpotRequest, userID uint, isAdmin bool) (*responses.SpotResponse, error) {
	ret := _m.Called(ctx, id, req, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *responses.SpotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.UpdateSpotRequest, uint, bool) (*responses.SpotResponse, error)); ok {
		return rf(ctx, id, req, userID, isAdmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.UpdateSpotRequest, uint, bool) *responses.SpotResponse); ok {
		r0 = rf(ctx, id, req, userID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.SpotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *requests.UpdateSpotRequest, uint, bool) error); ok {
		r1 = rf(ctx, id, req, userID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SpotService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - req *requests.UpdateSpotRequest
//   - userID uint
//   - isAdmin bool
func (_e *SpotService_Expecter) Update(ctx interface{}, id interface{}, req interface{}, userID interface{}, isAdmin interface{}) *SpotService_Update_Call {
	return &SpotService_Update_Call{Call: _e.mock.On("Update", ctx, id, req, userID, isAdmin)}
}

func (_c *SpotService_Update_Call) Run(run func(ctx context.Context, id uint, req *requests.UpdateSpotRequest, userID uint, isAdmin bool)) *SpotService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*requests.UpdateSpotRequest), args[3].(uint), args[4].(bool))
	})
	return _c
}

func (_c *SpotService_Update_Call) Return(_a0 *responses.SpotResponse, _a1 error) *SpotService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotService_Update_Call) RunAndReturn(run func(context.Context, uint, *requests.UpdateSpotRequest, uint, bool) (*responses.SpotResponse, error)) *SpotService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpotService creates a new instance of SpotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotService {
	mock := &SpotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
