// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "hopSpotAPI/internal/repository"
)

// SpotRepository is an autogenerated mock type for the SpotRepository type
type SpotRepository struct {
	mock.Mock
}

type SpotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SpotRepository) EXPECT() *SpotRepository_Expecter {
	return &SpotRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, spot
func (_m *SpotRepository) Create(ctx context.Context, spot *domain.Spot) error {
	ret := _m.Called(ctx, spot)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spot) error); ok {
		r0 = rf(ctx, spot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SpotRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spot *domain.Spot
func (_e *SpotRepository_Expecter) Create(ctx interface{}, spot interface{}) *SpotRepository_Create_Call {
	return &SpotRepository_Create_Call{Call: _e.mock.On("Create", ctx, spot)}
}

func (_c *SpotRepository_Create_Call) Run(run func(ctx context.Context, spot *domain.Spot)) *SpotRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Spot))
	})
	return _c
}

func (_c *SpotRepository_Create_Call) Return(_a0 error) *SpotRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Spot) error) *SpotRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SpotRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SpotRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *SpotRepository_Expecter) Delete(ctx interface{}, id interface{}) *SpotRepository_Delete_Call {
	return &SpotRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SpotRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *SpotRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *SpotRepository_Delete_Call) Return(_a0 error) *SpotRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *SpotRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *SpotRepository) FindAll(ctx context.Context, filter repository.SpotFilter) ([]domain.Spot, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Spot
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SpotFilter) ([]domain.Spot, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SpotFilter) []domain.Spot); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Spot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SpotFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.SpotFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SpotRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type SpotRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.SpotFilter
func (_e *SpotRepository_Expecter) FindAll(ctx interface{}, filter interface{}) *SpotRepository_FindAll_Call {
	return &SpotRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *SpotRepository_FindAll_Call) Run(run func(ctx context.Context, filter repository.SpotFilter)) *SpotRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SpotFilter))
	})
	return _c
}

func (_c *SpotRepository_FindAll_Call) Return(_a0 []domain.Spot, _a1 int64, _a2 error) *SpotRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *SpotRepository_FindAll_Call) RunAndReturn(run func(context.Context, repository.SpotFilter) ([]domain.Spot, int64, error)) *SpotRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindRandom provides a mock function with given fields: ctx
func (_m *SpotRepository) FindRandom(ctx context.Context) (*domain.Spot, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindRandom")
	}

	var r0 *domain.Spot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Spot, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Spot); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Spot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotRepository_FindRandom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRandom'
type SpotRepository_FindRandom_Call struct {
	*mock.Call
}

// FindRandom is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SpotRepository_Expecter) FindRandom(ctx interface{}) *SpotRepository_FindRandom_Call {
	return &SpotRepository_FindRandom_Call{Call: _e.mock.On("FindRandom", ctx)}
}

func (_c *SpotRepository_FindRandom_Call) Run(run func(ctx context.Context)) *SpotRepository_FindRandom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SpotRepository_FindRandom_Call) Return(_a0 *domain.Spot, _a1 error) *SpotRepository_FindRandom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotRepository_FindRandom_Call) RunAndReturn(run func(context.Context) (*domain.Spot, error)) *SpotRepository_FindRandom_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *SpotRepository) FindByID(ctx context.Context, id uint) (*domain.Spot, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Spot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Spot, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Spot); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Spot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpotRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type SpotRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *SpotRepository_Expecter) FindByID(ctx interface{}, id interface{}) *SpotRepository_FindByID_Call {
	return &SpotRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *SpotRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *SpotRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *SpotRepository_FindByID_Call) Return(_a0 *domain.Spot, _a1 error) *SpotRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpotRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Spot, error)) *SpotRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, spot
func (_m *SpotRepository) Update(ctx context.Context, spot *domain.Spot) error {
	ret := _m.Called(ctx, spot)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Spot) error); ok {
		r0 = rf(ctx, spot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SpotRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - spot *domain.Spot
func (_e *SpotRepository_Expecter) Update(ctx interface{}, spot interface{}) *SpotRepository_Update_Call {
	return &SpotRepository_Update_Call{Call: _e.mock.On("Update", ctx, spot)}
}

func (_c *SpotRepository_Update_Call) Run(run func(ctx context.Context, spot *domain.Spot)) *SpotRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Spot))
	})
	return _c
}

func (_c *SpotRepository_Update_Call) Return(_a0 error) *SpotRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Spot) error) *SpotRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFields provides a mock function with given fields: ctx, id, fields
func (_m *SpotRepository) UpdateFields(ctx context.Context, id uint, fields map[string]interface{}) error {
	ret := _m.Called(ctx, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFields")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, fields)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpotRepository_UpdateFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFields'
type SpotRepository_UpdateFields_Call struct {
	*mock.Call
}

// UpdateFields is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - fields map[string]interface{}
func (_e *SpotRepository_Expecter) UpdateFields(ctx interface{}, id interface{}, fields interface{}) *SpotRepository_UpdateFields_Call {
	return &SpotRepository_UpdateFields_Call{Call: _e.mock.On("UpdateFields", ctx, id, fields)}
}

func (_c *SpotRepository_UpdateFields_Call) Run(run func(ctx context.Context, id uint, fields map[string]interface{})) *SpotRepository_UpdateFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *SpotRepository_UpdateFields_Call) Return(_a0 error) *SpotRepository_UpdateFields_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpotRepository_UpdateFields_Call) RunAndReturn(run func(context.Context, uint, map[string]interface{}) error) *SpotRepository_UpdateFields_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpotRepository creates a new instance of SpotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpotRepository {
	mock := &SpotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
