// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	requests "hopSpotAPI/internal/dto/requests"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, req
func (_m *UserService) ChangePassword(ctx context.Context, userID uint, req *requests.ChangePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.ChangePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req *requests.ChangePasswordRequest
func (_e *UserService_Expecter) ChangePassword(ctx interface{}, userID interface{}, req interface{}) *UserService_ChangePassword_Call {
	return &UserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, req)}
}

func (_c *UserService_ChangePassword_Call) Run(run func(ctx context.Context, userID uint, req *requests.ChangePasswordRequest)) *UserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*requests.ChangePasswordRequest))
	})
	return _c
}

func (_c *UserService_ChangePassword_Call) Return(_a0 error) *UserService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserService_ChangePassword_Call) RunAndReturn(run func(context.Context, uint, *requests.ChangePasswordRequest) error) *UserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *UserService) GetProfile(ctx context.Context, userID uint) (*responses.UserResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *responses.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*responses.UserResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *responses.UserResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *UserService_Expecter) GetProfile(ctx interface{}, userID interface{}) *UserService_GetProfile_Call {
	return &UserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *UserService_GetProfile_Call) Run(run func(ctx context.Context, userID uint)) *UserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *UserService_GetProfile_Call) Return(_a0 *responses.UserResponse, _a1 error) *UserService_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_GetProfile_Call) RunAndReturn(run func(context.Context, uint) (*responses.UserResponse, error)) *UserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *UserService) UpdateProfile(ctx context.Context, userID uint, req *requests.UpdateProfileRequest) (*responses.UserResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *responses.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.UpdateProfileRequest) (*responses.UserResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *requests.UpdateProfileRequest) *responses.UserResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *requests.UpdateProfileRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - req *requests.UpdateProfileRequest
func (_e *UserService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *UserService_UpdateProfile_Call {
	return &UserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *UserService_UpdateProfile_Call) Run(run func(ctx context.Context, userID uint, req *requests.UpdateProfileRequest)) *UserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*requests.UpdateProfileRequest))
	})
	return _c
}

func (_c *UserService_UpdateProfile_Call) Return(_a0 *responses.UserResponse, _a1 error) *UserService_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_UpdateProfile_Call) RunAndReturn(run func(context.Context, uint, *requests.UpdateProfileRequest) (*responses.UserResponse, error)) *UserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
