// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	requests "hopSpotAPI/internal/dto/requests"

	mock "github.com/stretchr/testify/mock"

	responses "hopSpotAPI/internal/dto/responses"
)

// VisitService is an autogenerated mock type for the VisitService type
type VisitService struct {
	mock.Mock
}

type VisitService_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitService) EXPECT() *VisitService_Expecter {
	return &VisitService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req, userID
func (_m *VisitService) Create(ctx context.Context, req *requests.CreateVisitRequest, userID uint) (*responses.VisitResponse, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *responses.VisitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateVisitRequest, uint) (*responses.VisitResponse, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateVisitRequest, uint) *responses.VisitResponse); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.VisitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.CreateVisitRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.CreateVisitRequest
//   - userID uint
func (_e *VisitService_Expecter) Create(ctx interface{}, req interface{}, userID interface{}) *VisitService_Create_Call {
	return &VisitService_Create_Call{Call: _e.mock.On("Create", ctx, req, userID)}
}

func (_c *VisitService_Create_Call) Run(run func(ctx context.Context, req *requests.CreateVisitRequest, userID uint)) *VisitService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.CreateVisitRequest), args[2].(uint))
	})
	return _c
}

func (_c *VisitService_Create_Call) Return(_a0 *responses.VisitResponse, _a1 error) *VisitService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitService_Create_Call) RunAndReturn(run func(context.Context, *requests.CreateVisitRequest, uint) (*responses.VisitResponse, error)) *VisitService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetCountByBenchID provides a mock function with given fields: ctx, benchID
func (_m *VisitService) GetCountByBenchID(ctx context.Context, benchID uint) (int64, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for GetCountByBenchID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, benchID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitService_GetCountByBenchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCountByBenchID'
type VisitService_GetCountByBenchID_Call struct {
	*mock.Call
}

// GetCountByBenchID is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *VisitService_Expecter) GetCountByBenchID(ctx interface{}, benchID interface{}) *VisitService_GetCountByBenchID_Call {
	return &VisitService_GetCountByBenchID_Call{Call: _e.mock.On("GetCountByBenchID", ctx, benchID)}
}

func (_c *VisitService_GetCountByBenchID_Call) Run(run func(ctx context.Context, benchID uint)) *VisitService_GetCountByBenchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *VisitService_GetCountByBenchID_Call) Return(_a0 int64, _a1 error) *VisitService_GetCountByBenchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitService_GetCountByBenchID_Call) RunAndReturn(run func(context.Context, uint) (int64, error)) *VisitService_GetCountByBenchID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req, userID
func (_m *VisitService) List(ctx context.Context, req *requests.ListVisitsRequest, userID uint) (*responses.PaginatedVisitsResponse, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *responses.PaginatedVisitsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListVisitsRequest, uint) (*responses.PaginatedVisitsResponse, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *requests.ListVisitsRequest, uint) *responses.PaginatedVisitsResponse); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.PaginatedVisitsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *requests.ListVisitsRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type VisitService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req *requests.ListVisitsRequest
//   - userID uint
func (_e *VisitService_Expecter) List(ctx interface{}, req interface{}, userID interface{}) *VisitService_List_Call {
	return &VisitService_List_Call{Call: _e.mock.On("List", ctx, req, userID)}
}

func (_c *VisitService_List_Call) Run(run func(ctx context.Context, req *requests.ListVisitsRequest, userID uint)) *VisitService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*requests.ListVisitsRequest), args[2].(uint))
	})
	return _c
}

func (_c *VisitService_List_Call) Return(_a0 *responses.PaginatedVisitsResponse, _a1 error) *VisitService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitService_List_Call) RunAndReturn(run func(context.Context, *requests.ListVisitsRequest, uint) (*responses.PaginatedVisitsResponse, error)) *VisitService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitService creates a new instance of VisitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitService {
	mock := &VisitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
