// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "hopSpotAPI/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "hopSpotAPI/internal/repository"
)

// VisitRepository is an autogenerated mock type for the VisitRepository type
type VisitRepository struct {
	mock.Mock
}

type VisitRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VisitRepository) EXPECT() *VisitRepository_Expecter {
	return &VisitRepository_Expecter{mock: &_m.Mock}
}

// CountByBenchID provides a mock function with given fields: ctx, benchID
func (_m *VisitRepository) CountByBenchID(ctx context.Context, benchID uint) (int64, error) {
	ret := _m.Called(ctx, benchID)

	if len(ret) == 0 {
		panic("no return value specified for CountByBenchID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int64, error)); ok {
		return rf(ctx, benchID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int64); ok {
		r0 = rf(ctx, benchID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, benchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRepository_CountByBenchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBenchID'
type VisitRepository_CountByBenchID_Call struct {
	*mock.Call
}

// CountByBenchID is a helper method to define mock.On call
//   - ctx context.Context
//   - benchID uint
func (_e *VisitRepository_Expecter) CountByBenchID(ctx interface{}, benchID interface{}) *VisitRepository_CountByBenchID_Call {
	return &VisitRepository_CountByBenchID_Call{Call: _e.mock.On("CountByBenchID", ctx, benchID)}
}

func (_c *VisitRepository_CountByBenchID_Call) Run(run func(ctx context.Context, benchID uint)) *VisitRepository_CountByBenchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *VisitRepository_CountByBenchID_Call) Return(_a0 int64, _a1 error) *VisitRepository_CountByBenchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRepository_CountByBenchID_Call) RunAndReturn(run func(context.Context, uint) (int64, error)) *VisitRepository_CountByBenchID_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, visit
func (_m *VisitRepository) Create(ctx context.Context, visit *domain.Visit) error {
	ret := _m.Called(ctx, visit)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Visit) error); ok {
		r0 = rf(ctx, visit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type VisitRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - visit *domain.Visit
func (_e *VisitRepository_Expecter) Create(ctx interface{}, visit interface{}) *VisitRepository_Create_Call {
	return &VisitRepository_Create_Call{Call: _e.mock.On("Create", ctx, visit)}
}

func (_c *VisitRepository_Create_Call) Run(run func(ctx context.Context, visit *domain.Visit)) *VisitRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Visit))
	})
	return _c
}

func (_c *VisitRepository_Create_Call) Return(_a0 error) *VisitRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Visit) error) *VisitRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VisitRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VisitRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type VisitRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *VisitRepository_Expecter) Delete(ctx interface{}, id interface{}) *VisitRepository_Delete_Call {
	return &VisitRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *VisitRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *VisitRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *VisitRepository_Delete_Call) Return(_a0 error) *VisitRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VisitRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *VisitRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *VisitRepository) FindByID(ctx context.Context, id uint) (*domain.Visit, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Visit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Visit, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Visit); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VisitRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type VisitRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *VisitRepository_Expecter) FindByID(ctx interface{}, id interface{}) *VisitRepository_FindByID_Call {
	return &VisitRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *VisitRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *VisitRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *VisitRepository_FindByID_Call) Return(_a0 *domain.Visit, _a1 error) *VisitRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VisitRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Visit, error)) *VisitRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID, filter
func (_m *VisitRepository) FindByUserID(ctx context.Context, userID uint, filter repository.VisitFilter) ([]domain.Visit, int64, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []domain.Visit
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, repository.VisitFilter) ([]domain.Visit, int64, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, repository.VisitFilter) []domain.Visit); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Visit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, repository.VisitFilter) int64); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint, repository.VisitFilter) error); ok {
		r2 = rf(ctx, userID, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VisitRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type VisitRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filter repository.VisitFilter
func (_e *VisitRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}, filter interface{}) *VisitRepository_FindByUserID_Call {
	return &VisitRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID, filter)}
}

func (_c *VisitRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uint, filter repository.VisitFilter)) *VisitRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(repository.VisitFilter))
	})
	return _c
}

func (_c *VisitRepository_FindByUserID_Call) Return(_a0 []domain.Visit, _a1 int64, _a2 error) *VisitRepository_FindByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *VisitRepository_FindByUserID_Call) RunAndReturn(run func(context.Context, uint, repository.VisitFilter) ([]domain.Visit, int64, error)) *VisitRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewVisitRepository creates a new instance of VisitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVisitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VisitRepository {
	mock := &VisitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
