// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	responses "hopSpotAPI/internal/dto/responses"

	mock "github.com/stretchr/testify/mock"
)

// WeatherService is an autogenerated mock type for the WeatherService type
type WeatherService struct {
	mock.Mock
}

type WeatherService_Expecter struct {
	mock *mock.Mock
}

func (_m *WeatherService) EXPECT() *WeatherService_Expecter {
	return &WeatherService_Expecter{mock: &_m.Mock}
}

// GetCurrentWeather provides a mock function with given fields: ctx, lat, lon
func (_m *WeatherService) GetCurrentWeather(ctx context.Context, lat float64, lon float64) (*responses.WeatherResponse, error) {
	ret := _m.Called(ctx, lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentWeather")
	}

	var r0 *responses.WeatherResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (*responses.WeatherResponse, error)); ok {
		return rf(ctx, lat, lon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) *responses.WeatherResponse); ok {
		r0 = rf(ctx, lat, lon)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.WeatherResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lat, lon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WeatherService_GetCurrentWeather_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentWeather'
type WeatherService_GetCurrentWeather_Call struct {
	*mock.Call
}

// GetCurrentWeather is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lon float64
func (_e *WeatherService_Expecter) GetCurrentWeather(ctx interface{}, lat interface{}, lon interface{}) *WeatherService_GetCurrentWeather_Call {
	return &WeatherService_GetCurrentWeather_Call{Call: _e.mock.On("GetCurrentWeather", ctx, lat, lon)}
}

func (_c *WeatherService_GetCurrentWeather_Call) Run(run func(ctx context.Context, lat float64, lon float64)) *WeatherService_GetCurrentWeather_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *WeatherService_GetCurrentWeather_Call) Return(_a0 *responses.WeatherResponse, _a1 error) *WeatherService_GetCurrentWeather_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WeatherService_GetCurrentWeather_Call) RunAndReturn(run func(context.Context, float64, float64) (*responses.WeatherResponse, error)) *WeatherService_GetCurrentWeather_Call {
	_c.Call.Return(run)
	return _c
}

// NewWeatherService creates a new instance of WeatherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherService {
	mock := &WeatherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
